# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# baseURL = "https://your_domain.com/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 20

# title = "KSCU 103.3 FM | The Underground Sound"
# description = "Tune in to the Underground Sound."
# copyright = "CC 2022"

googleAnalytics = "G-LTQTS3WW1X"

[outputs]
  home = ["HTML", "RSS", "JSON"]
